APP_TITLE = "KeyTune"
APP_VERSION = "1.0.0"
DEFAULT_WINDOW_SIZE = (980, 620)
DEFAULT_VOLUME = 80
DEFAULT_CROSSFADE_SECONDS = 0
DEFAULT_CROSSFADE_ON_MANUAL_TRACK_CHANGE = False
SEEK_STEP_MS = 5000
LARGE_SEEK_STEP_MS = 60000
VOLUME_STEP = 5
PROGRESS_GAUGE_RANGE = 1000
PROGRESS_TIMER_INTERVAL_MS = 500
CROSSFADE_TIMER_INTERVAL_MS = 15
MAX_CROSSFADE_SECONDS = 12
SHORT_FADE_MS = 180
SHORT_FADE_STEPS = 8
PLAYBACK_RESTART_THRESHOLD_MS = 3000
EXPLORER_PREVIEW_DELAY_MS = 120
STARTUP_UPDATE_CHECK_DELAY_MS = 2000
UPDATE_HTTP_TIMEOUT_SECONDS = 20
UPDATE_DOWNLOAD_CHUNK_SIZE = 256 * 1024
DEFAULT_RESTORE_SESSION_ON_STARTUP = True
DEFAULT_REMEMBER_WINDOW_SIZE = True
DEFAULT_REMEMBER_LAST_FOLDER = True
DEFAULT_CONFIRM_ON_EXIT = False
DEFAULT_ANNOUNCEMENTS_ENABLED = True
DEFAULT_DISABLE_VIDEO_OUTPUT = True
DEFAULT_NEW_PLAYLIST_SHUFFLE = False
DEFAULT_YOUTUBE_MUSIC_MANAGE_DEPENDENCIES = False
DEFAULT_YOUTUBE_MUSIC_AUTO_UPDATE_DEPENDENCIES = True
DEFAULT_YOUTUBE_MUSIC_USE_NIGHTLY_YT_DLP = True
DEFAULT_YOUTUBE_MUSIC_DEPENDENCY_UPDATE_INTERVAL_HOURS = 24
DEFAULT_YOUTUBE_MUSIC_LIBRARY_PAGE_SIZE = 25
DEFAULT_YOUTUBE_MUSIC_HOME_DISCOVERY_LIMIT = 30
MIN_YOUTUBE_MUSIC_LIBRARY_PAGE_SIZE = 5
MAX_YOUTUBE_MUSIC_LIBRARY_PAGE_SIZE = 200
MIN_YOUTUBE_MUSIC_HOME_DISCOVERY_LIMIT = 5
MAX_YOUTUBE_MUSIC_HOME_DISCOVERY_LIMIT = 200
RECENT_ITEMS_LIMIT = 10

GITHUB_REPOSITORY_OWNER = "ed-fe"
GITHUB_REPOSITORY_NAME = "KeyTune"
# Installer-driven updates: the app downloads and silently runs the setup .exe.
WINDOWS_SETUP_EXECUTABLE_NAME = "KeyTune-Setup.exe"
WINDOWS_SETUP_CHECKSUM_NAME = f"{WINDOWS_SETUP_EXECUTABLE_NAME}.sha256"

DEFAULT_LOGGING_ENABLED = True
DEFAULT_LOGGING_LEVEL = "WARNING"
LOGGING_LEVELS = ("DEBUG", "INFO", "WARNING", "ERROR")
LOGGING_LEVEL_LABELS = {
    "DEBUG": "Depuração (DEBUG)",
    "INFO": "Informativo (INFO)",
    "WARNING": "Avisos (WARNING)",
    "ERROR": "Apenas erros (ERROR)",
}

REPEAT_OFF = "off"
REPEAT_ONE = "one"
REPEAT_ALL = "all"
REPEAT_MODES = (REPEAT_OFF, REPEAT_ONE, REPEAT_ALL)
REPEAT_MODE_LABELS = {
    REPEAT_OFF: "Repetição desligada",
    REPEAT_ONE: "Repetir faixa atual",
    REPEAT_ALL: "Repetir playlist",
}

PLAYLIST_WILDCARD = (
    "Playlists|*.m3u;*.m3u8|"
    "Playlist M3U8|*.m3u8|"
    "Playlist M3U|*.m3u|"
    "Todos os arquivos|*.*"
)

# Standard container/codec extensions playable by the bundled MPV (FFmpeg)
# runtime, mirroring what mainstream players (VLC, MPC-HC) offer for
# association. Keep these in sync with installer/keytune.iss.
VIDEO_EXTENSIONS = {
    ".mp4",
    ".m4v",
    ".mkv",
    ".avi",
    ".mov",
    ".webm",
    ".flv",
    ".wmv",
    ".mpg",
    ".mpeg",
    ".3gp",
    ".ts",
    ".m2ts",
    ".mts",
    ".ogv",
}

AUDIO_ONLY_EXTENSIONS = {
    ".mp3",
    ".wav",
    ".flac",
    ".aac",
    ".ogg",
    ".oga",
    ".m4a",
    ".opus",
    ".wma",
    ".aiff",
    ".aif",
    ".ac3",
    ".mka",
    ".wv",
    ".ape",
}

SUPPORTED_MEDIA_EXTENSIONS = VIDEO_EXTENSIONS | AUDIO_ONLY_EXTENSIONS
