FOLDER_SORT_NAME = "name"
FOLDER_SORT_MODIFIED = "modified"
FOLDER_SORT_CREATED = "created"
FOLDER_SORT_TYPE = "type"
FOLDER_SORT_SIZE = "size"
FOLDER_SORT_OPTIONS = {
    FOLDER_SORT_NAME,
    FOLDER_SORT_MODIFIED,
    FOLDER_SORT_CREATED,
    FOLDER_SORT_TYPE,
    FOLDER_SORT_SIZE,
}
